# Generated by Django 3.1.1 on 2020-09-12 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='items',
            new_name='ident',
        ),
    ]
