# Generated by Django 3.1.1 on 2020-09-13 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20200912_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=200)),
                ('Last_Name', models.CharField(max_length=200)),
                ('Email_Address', models.CharField(max_length=200)),
                ('Portfolio', models.CharField(max_length=200)),
                ('Position', models.CharField(max_length=200)),
                ('Salary', models.CharField(max_length=200)),
                ('StartDate', models.CharField(max_length=200)),
                ('Phone', models.CharField(max_length=20)),
                ('Fax', models.CharField(max_length=20)),
                ('Organization', models.CharField(max_length=100)),
                ('skip_CaptchaCode', models.CharField(max_length=6)),
            ],
        ),
    ]
